// Package tts implements the text-to-speech stage of the bookai pipeline.
//
// The package is built around the Engine interface, which abstracts the actual
// speech synthesis backend. This lets the pipeline structure (text
// preprocessing, audio output, ffmpeg post-processing) be built and tested
// independently of any specific TTS engine. Concrete engines (noop,
// silero-http, etc.) are registered via Register and selected by name from
// config.
package tts

import (
	"context"
	"fmt"
	"sort"
	"strings"
	"sync"
)

// Engine synthesizes speech from SSML input. Implementations may be local
// (subprocess, ONNX runtime) or remote (HTTP API). The interface is
// intentionally minimal: the caller provides SSML text and an output path;
// the engine writes a WAV file to that path.
type Engine interface {
	// Name returns the engine identifier (e.g. "noop", "silero-http").
	Name() string

	// Synthesize converts SSML text into speech and writes a WAV file to
	// outPath. The text is SSML (with <speak> root tag and stress marks)
	// generated by the ssml command. outPath's parent directory is guaranteed
	// to exist by the caller.
	Synthesize(ctx context.Context, text string, outPath string) error
}

// EngineFactory constructs an Engine from the TTS configuration. Factories are
// registered at init time by each engine implementation. Returning an error
// (e.g. missing model path, unavailable runtime) lets the CLI surface a clear
// message before any synthesis is attempted.
type EngineFactory func(cfg EngineConfig) (Engine, error)

// EngineConfig is the configuration passed to an EngineFactory. It is derived
// from config.TTS by the CLI layer, with absolute paths resolved.
type EngineConfig struct {
	// Engine is the engine name (matches the factory key).
	Engine string

	// Language is the target language code (e.g. "ru").
	Language string

	// Voice is the Silero voice ID (e.g. "silero:v5_5_ru#xenia"). Used by
	// the silero-http engine.
	Voice string

	// Speed is a playback speed multiplier (1.0 = normal). Engines may
	// ignore this.
	Speed float64

	// Pitch is a pitch multiplier (1.0 = normal). Used by the silero-http
	// engine.
	Pitch float64

	// SampleRate is the output sample rate (48000 for Silero). Used by the
	// silero-http engine.
	SampleRate int

	// ServerURL is the HTTP endpoint for remote TTS engines (e.g.
	// "http://localhost:5555"). Used by the silero-http engine.
	ServerURL string

	// Parallel is the number of concurrent API requests to send when
	// synthesizing a single chapter (chunk-level parallelism). Default 0
	// or 1 means sequential. Higher values can speed up synthesis when the
	// TTS server has spare capacity.
	Parallel int
}

var (
	registryMu sync.RWMutex                     //nolint:gochecknoglobals // engine registry state
	registry   = make(map[string]EngineFactory) //nolint:gochecknoglobals // engine registry state

	registerBuiltinsOnce sync.Once //nolint:gochecknoglobals // guards one-time registration of built-in engines
)

// RegisterEngines registers all built-in engine factories. Safe to call
// multiple times; subsequent calls are no-ops. Also called automatically by
// NewEngine and AvailableEngines so that consumers outside the bookai binary
// RegisterEngines registers the built-in text-to-speech engines once. Subsequent calls have no effect.
func RegisterEngines() {
	registerBuiltinsOnce.Do(func() {
		Register(engineNoop, NewNoopEngine)
		Register(engineSileroHTTP, NewSileroEngine)
	})
}

// ensureRegistered makes sure built-in engines are in the registry. Called
// by NewEngine and AvailableEngines so callers don't need to call
// ensureRegistered ensures that the built-in text-to-speech engines are registered.
func ensureRegistered() {
	RegisterEngines()
}

// Register adds an EngineFactory under the given name. Panics if the name is
// Register adds an engine factory under the specified name and panics if the name is already registered.
func Register(name string, factory EngineFactory) {
	registryMu.Lock()
	defer registryMu.Unlock()
	if _, exists := registry[name]; exists {
		panic(fmt.Sprintf("tts: engine %q already registered", name))
	}
	registry[name] = factory
}

// NewEngine looks up the registered factory for cfg.Engine and constructs an
// Engine. Returns a descriptive error if the engine is unknown or
// It returns an error if the configured engine is unknown or initialization fails.
func NewEngine(cfg EngineConfig) (Engine, error) {
	ensureRegistered()
	registryMu.RLock()
	factory, ok := registry[cfg.Engine]
	registryMu.RUnlock()
	if !ok {
		return nil, fmt.Errorf("tts: unknown engine %q (available: %s)", cfg.Engine, AvailableEngines())
	}
	engine, err := factory(cfg)
	if err != nil {
		return nil, fmt.Errorf("tts: init engine %q: %w", cfg.Engine, err)
	}
	return engine, nil
}

// AvailableEngines returns the sorted list of registered engine names.
func AvailableEngines() string {
	ensureRegistered()
	registryMu.RLock()
	names := make([]string, 0, len(registry))
	for name := range registry {
		names = append(names, name)
	}
	registryMu.RUnlock()
	sort.Strings(names)
	return joinNames(names)
}

// joinNames formats engine names as a comma-separated list for error messages.
func joinNames(names []string) string {
	if len(names) == 0 {
		return "(none)"
	}
	result := ""
	var resultSb127 strings.Builder
	for i, n := range names {
		if i > 0 {
			resultSb127.WriteString(", ")
		}
		resultSb127.WriteString(n)
	}
	result += resultSb127.String()
	return result
}
