package tts

import (
	"context"
	"encoding/binary"
	"fmt"
	"math"
	"os"
	"time"
)

// Engine name and WAV format constants shared across TTS engine files.
const (
	engineNoop       = "noop"
	engineSileroHTTP = "silero-http"
	wavRIFF          = "RIFF"
	wavWAVE          = "WAVE"
)

// noopFreq is the frequency (Hz) of the sine tone generated by the noop engine.
const noopFreq = 220.0

// noopSampleRate is the sample rate (Hz) used by the noop engine's WAV output.
const noopSampleRate = 16000

// noopTextDivisor scales text length into seconds for the noop tone duration.
const noopTextDivisor = 2000.0

// noopDurationSec is the maximum tone duration (in seconds) produced by the
// noop engine.
const noopDurationSec = 3.0

// noopBaseDurationSec is the base tone duration (in seconds) before scaling
// by text length.
const noopBaseDurationSec = 0.5

// fadeRatio is the amplitude multiplier applied to the sine wave (prevents
// full-scale clipping).
const fadeRatio = 0.2

// bytesPerSample is the number of bytes per 16-bit PCM sample.
const bytesPerSample = 2

// WAV header size constants (in bytes) used by writeWAV.
const (
	wavHeaderSize    = 36 // RIFF header size excluding data chunk
	wavFmtChunkSize  = 16 // fmt chunk size for PCM
	wavPCMFormat     = 1  // PCM audio format code
	wavMonoChannels  = 1  // mono channel count
	wavBitsPerSample = 16 // 16-bit PCM
	wavBlockAlign    = 2  // bytes per sample frame (mono 16-bit)
)

// NoopEngine is a default Engine that writes a minimal valid WAV file
// containing a short tone. It requires no external dependencies and is used
// when no real TTS engine is configured, allowing the full pipeline
// (preprocess → audio) to be tested end-to-end without a speech synthesis
// backend.
type NoopEngine struct {
	cfg EngineConfig
}

// NewNoopEngine constructs a NoopEngine from the given config. The config is
// NewNoopEngine creates a dependency-free no-op TTS engine with the specified configuration.
func NewNoopEngine(cfg EngineConfig) (Engine, error) {
	return &NoopEngine{cfg: cfg}, nil
}

// Name returns "noop".
func (e *NoopEngine) Name() string { return engineNoop }

// Synthesize writes a short sine-tone WAV to outPath. The tone duration scales
// mildly with input length so that downstream merge logic has varied file
// sizes to work with. The text is not parsed — this engine exists for
// pipeline testing only.
func (e *NoopEngine) Synthesize(_ context.Context, text string, outPath string) error {
	duration := noopDuration(len(text))
	samples := noopSineWave(noopFreq, duration, noopSampleRate)
	return writeWAV(outPath, samples, noopSampleRate)
}

// noopDuration returns a duration between 0.5s and 3s based on text length,
// noopDuration calculates a capped audio duration from the input text length.
func noopDuration(textLen int) time.Duration {
	if textLen < 0 {
		textLen = 0
	}
	secs := noopBaseDurationSec + float64(textLen)/noopTextDivisor
	if secs > noopDurationSec {
		secs = noopDurationSec
	}
	return time.Duration(secs * float64(time.Second))
}

// noopSineWave generates mono 16-bit PCM samples for the specified frequency, duration, and sample rate.
func noopSineWave(freq float64, duration time.Duration, sampleRate int) []int16 {
	numSamples := int(duration.Seconds() * float64(sampleRate))
	samples := make([]int16, numSamples)
	for i := range samples {
		t := float64(i) / float64(sampleRate)
		val := math.Sin(2*math.Pi*freq*t) * fadeRatio * float64(math.MaxInt16)
		samples[i] = int16(val)
	}
	return samples
}

// writeWAV writes samples to a mono, 16-bit PCM WAV file at the specified sample rate.
func writeWAV(path string, samples []int16, sampleRate int) error {
	if sampleRate < 0 || sampleRate > math.MaxUint32/2 {
		return fmt.Errorf("invalid sample rate: %d", sampleRate)
	}
	f, err := os.Create(path)
	if err != nil {
		return fmt.Errorf("create %s: %w", path, err)
	}
	defer func() { _ = f.Close() }()

	dataSize := len(samples) * bytesPerSample // 16-bit = 2 bytes per sample
	if dataSize > math.MaxUint32-wavHeaderSize {
		return fmt.Errorf("WAV data too large: %d bytes", dataSize)
	}
	// RIFF header
	if _, err = f.WriteString(wavRIFF); err != nil {
		return err
	}
	if err = binary.Write(f, binary.LittleEndian, uint32(wavHeaderSize+dataSize)); err != nil {
		return err
	}
	if _, err = f.WriteString(wavWAVE); err != nil {
		return err
	}
	// fmt chunk
	if _, err = f.WriteString("fmt "); err != nil {
		return err
	}
	if err = binary.Write(f, binary.LittleEndian, uint32(wavFmtChunkSize)); err != nil { // chunk size
		return err
	}
	if err = binary.Write(f, binary.LittleEndian, uint16(wavPCMFormat)); err != nil { // PCM
		return err
	}
	if err = binary.Write(f, binary.LittleEndian, uint16(wavMonoChannels)); err != nil { // mono
		return err
	}
	if err = binary.Write(f, binary.LittleEndian, uint32(sampleRate)); err != nil {
		return err
	}
	if err = binary.Write(f, binary.LittleEndian, uint32(sampleRate*wavBlockAlign)); err != nil { // byte rate
		return err
	}
	if err = binary.Write(f, binary.LittleEndian, uint16(wavBlockAlign)); err != nil { // block align
		return err
	}
	if err = binary.Write(f, binary.LittleEndian, uint16(wavBitsPerSample)); err != nil { // bits per sample
		return err
	}
	// data chunk
	if _, err = f.WriteString("data"); err != nil {
		return err
	}
	if err = binary.Write(f, binary.LittleEndian, uint32(dataSize)); err != nil {
		return err
	}
	for _, s := range samples {
		if err = binary.Write(f, binary.LittleEndian, s); err != nil {
			return err
		}
	}
	return nil
}
