package tts

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"log/slog"
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"time"
)

// SileroEngine is an Engine that synthesizes speech via a remote Silero TTS
// server (biblio-tts-server-silero). It sends SSML text to the server's
// POST /api/tts endpoint and writes the returned WAV audio to the output path.
//
// The engine receives SSML text (with stress marks and <speak>/<p>/<s> tags)
// generated by the `bookai ssml` command. Silero natively supports stress
// marks (+ before the stressed vowel) and SSML tags for pause/prosody control.
type SileroEngine struct {
	cfg        EngineConfig
	client     *http.Client
	serverURL  string
}

// NewSileroEngine constructs a SileroEngine from the given config. The
// ServerURL and Voice fields are required. The engine uses a 10-minute timeout
// to accommodate long chapter synthesis on first model load.
func NewSileroEngine(cfg EngineConfig) (Engine, error) {
	if cfg.ServerURL == "" {
		return nil, fmt.Errorf("tts.silero: server_url is required")
	}
	if cfg.Voice == "" {
		return nil, fmt.Errorf("tts.silero: voice is required (e.g. \"silero:v5_5_ru#xenia\")")
	}
	serverURL := strings.TrimRight(cfg.ServerURL, "/")
	return &SileroEngine{
		cfg:       cfg,
		serverURL: serverURL,
		client: &http.Client{
			Timeout: 10 * time.Minute,
		},
	}, nil
}

// Name returns "silero-http".
func (e *SileroEngine) Name() string { return "silero-http" }

// sileroRequestBody is the JSON body sent to the POST /api/tts endpoint.
type sileroRequestBody struct {
	Text       string  `json:"text"`
	Voice      string  `json:"voice"`
	SSML       bool    `json:"ssml"`
	SampleRate int     `json:"sample_rate"`
	Speed      float64 `json:"speed"`
	Pitch      float64 `json:"pitch"`
}

// Synthesize sends SSML text to the Silero TTS server and writes the returned
// WAV audio to outPath. The text is expected to be SSML (with <speak> root
// tag and stress marks) generated by the `bookai ssml` command.
func (e *SileroEngine) Synthesize(ctx context.Context, text string, outPath string) error {
	if text == "" {
		return fmt.Errorf("tts.silero: no text to synthesize")
	}

	sampleRate := e.cfg.SampleRate
	if sampleRate == 0 {
		sampleRate = 48000
	}

	body := sileroRequestBody{
		Text:       text,
		Voice:      e.cfg.Voice,
		SSML:       true,
		SampleRate: sampleRate,
		Speed:      e.cfg.Speed,
		Pitch:      e.cfg.Pitch,
	}

	bodyJSON, err := json.Marshal(body)
	if err != nil {
		return fmt.Errorf("tts.silero: marshal request: %w", err)
	}

	url := e.serverURL + "/api/tts"
	slog.Debug("tts.silero: sending synthesis request",
		"url", url, "text_len", len(text), "voice", body.Voice)

	req, err := http.NewRequestWithContext(ctx, http.MethodPost, url, bytes.NewReader(bodyJSON))
	if err != nil {
		return fmt.Errorf("tts.silero: create request: %w", err)
	}
	req.Header.Set("Content-Type", "application/json")

	resp, err := e.client.Do(req)
	if err != nil {
		return fmt.Errorf("tts.silero: request failed: %w", err)
	}
	defer func() { _ = resp.Body.Close() }()

	if resp.StatusCode != http.StatusOK {
		respBody, _ := io.ReadAll(resp.Body)
		return fmt.Errorf("tts.silero: server returned %d: %s", resp.StatusCode, string(respBody))
	}

	if err := os.MkdirAll(filepath.Dir(outPath), 0o755); err != nil {
		return fmt.Errorf("tts.silero: create output dir: %w", err)
	}

	out, err := os.Create(outPath)
	if err != nil {
		return fmt.Errorf("tts.silero: create output file: %w", err)
	}
	defer func() { _ = out.Close() }()

	if _, err := io.Copy(out, resp.Body); err != nil {
		return fmt.Errorf("tts.silero: write audio: %w", err)
	}

	slog.Debug("tts.silero: synthesis complete", "output", outPath)
	return nil
}

// CheckHealth pings the server's /health endpoint. Returns nil if the server
// is reachable and responsive.
func (e *SileroEngine) CheckHealth(ctx context.Context) error {
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, e.serverURL+"/health", nil)
	if err != nil {
		return fmt.Errorf("tts.silero: create health request: %w", err)
	}
	resp, err := e.client.Do(req)
	if err != nil {
		return fmt.Errorf("tts.silero: health check failed: %w", err)
	}
	defer func() { _ = resp.Body.Close() }()
	if resp.StatusCode != http.StatusOK {
		return fmt.Errorf("tts.silero: health check returned %d", resp.StatusCode)
	}
	return nil
}

func init() {
	Register("silero-http", NewSileroEngine)
}
