package tts

import (
	"bytes"
	"context"
	"encoding/binary"
	"encoding/json"
	"fmt"
	"io"
	"log/slog"
	"math"
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"time"
)

// sileroTimeoutMinutes is the HTTP client timeout (in minutes) for Silero
// TTS requests, accommodating long chapter synthesis and first model load.
const sileroTimeoutMinutes = 10

// chunkHeaderSize is the size (in bytes) of a WAV chunk header (4-byte ID +
// 4-byte size).
const chunkHeaderSize = 8

// minWAVHeaderSize is the minimum number of bytes required for a valid WAV
// header (RIFF + WAVE + fmt + data chunk headers).
const minWAVHeaderSize = 44

// maxChunkLen is the maximum SSML text length sent to Silero in a single
// request. Silero warns at 1000 symbols and fails at longer text, so we
// stay well below that with 900.
const maxChunkLen = 900

// SileroEngine is an Engine that synthesizes speech via a remote Silero TTS
// server (biblio-tts-server-silero). It sends SSML text to the server's
// POST /api/tts endpoint and writes the returned WAV audio to the output path.
//
// The engine receives SSML text (with stress marks and <speak>/<p>/<s> tags)
// generated by the `bookai ssml` command. Silero natively supports stress
// marks (+ before the stressed vowel) and SSML tags for pause/prosody control.
//
// Long chapters are automatically split into chunks under maxChunkLen
// characters (split on sentence boundaries), synthesized separately, and the
// resulting WAV PCM data is concatenated into a single output file.
type SileroEngine struct {
	cfg       EngineConfig
	client    *http.Client
	serverURL string
	parallel  int
}

// NewSileroEngine constructs a SileroEngine from the given config. The
// ServerURL and Voice fields are required. The engine uses a 10-minute timeout
// to accommodate long chapter synthesis on first model load.
func NewSileroEngine(cfg EngineConfig) (Engine, error) {
	if cfg.ServerURL == "" {
		return nil, fmt.Errorf("tts.silero: server_url is required")
	}
	if cfg.Voice == "" {
		return nil, fmt.Errorf("tts.silero: voice is required (e.g. \"silero:v5_5_ru#xenia\")")
	}
	serverURL := strings.TrimRight(cfg.ServerURL, "/")
	parallel := max(cfg.Parallel, 1)
	return &SileroEngine{
		cfg:       cfg,
		serverURL: serverURL,
		parallel:  parallel,
		client: &http.Client{
			Timeout: time.Duration(sileroTimeoutMinutes) * time.Minute,
		},
	}, nil
}

// Name returns "silero-http".
func (e *SileroEngine) Name() string { return engineSileroHTTP }

// sileroRequestBody is the JSON body sent to the POST /api/tts endpoint.
type sileroRequestBody struct {
	Text       string  `json:"text"`
	Voice      string  `json:"voice"`
	SSML       bool    `json:"ssml"`
	SampleRate int     `json:"sample_rate"`
	Speed      float64 `json:"speed"`
	Pitch      float64 `json:"pitch"`
}

// Synthesize sends SSML text to the Silero TTS server and writes the returned
// WAV audio to outPath. The text is expected to be SSML (with <speak> root
// tag and stress marks) generated by the `bookai ssml` command.
//
// If the text exceeds maxChunkLen characters, it is split on sentence
// boundaries (<s>...</s> tags), each chunk is synthesized separately, and the
// WAV PCM data is concatenated into a single output file.
func (e *SileroEngine) Synthesize(ctx context.Context, text string, outPath string) error {
	if text == "" {
		return fmt.Errorf("tts.silero: no text to synthesize")
	}

	chunks := splitSSML(text)
	slog.Default().InfoContext(ctx, "tts.silero: synthesizing",
		"total_len", len(text), "chunks", len(chunks), "max_chunk_len", maxChunkLen,
		"parallel", e.parallel)

	wavData, err := e.synthesizeChunks(ctx, chunks)
	if err != nil {
		return err
	}

	if err = os.MkdirAll(filepath.Dir(outPath), 0o750); err != nil {
		return fmt.Errorf("tts.silero: create output dir: %w", err)
	}

	combined, err := concatWAVs(wavData)
	if err != nil {
		return fmt.Errorf("tts.silero: concat WAVs: %w", err)
	}

	if err = os.WriteFile(outPath, combined, 0o600); err != nil {
		return fmt.Errorf("tts.silero: write output: %w", err)
	}

	slog.Default().DebugContext(ctx, "tts.silero: synthesis complete", "output", outPath, "bytes", len(combined))
	return nil
}

// chunkJob is a unit of work for parallel chunk synthesis: the chunk's index
// in the original slice (so results can be placed in order) and its SSML text.
type chunkJob struct {
	idx   int
	chunk string
}

// synthesizeChunks sends chunk requests to the server, optionally in parallel.
// Results are collected in chunk order (the order they appear in the input
// slice) so the concatenated audio preserves sentence order.
func (e *SileroEngine) synthesizeChunks(ctx context.Context, chunks []string) ([][]byte, error) {
	n := len(chunks)
	if n == 0 {
		return nil, nil
	}

	// Sequential path (default) — simple and predictable.
	if e.parallel <= 1 {
		wavData := make([][]byte, n)
		for i, chunk := range chunks {
			if ctx.Err() != nil {
				return nil, ctx.Err()
			}
			slog.Default().DebugContext(ctx, "tts.silero: synthesizing chunk",
				"chunk", i+1, "of", n, "len", len(chunk))
			wav, err := e.synthesizeOne(ctx, chunk)
			if err != nil {
				return nil, fmt.Errorf("tts.silero: chunk %d/%d: %w", i+1, n, err)
			}
			wavData[i] = wav
		}
		return wavData, nil
	}

	// Parallel path — send up to e.parallel chunk requests concurrently.
	wavData := make([][]byte, n)
	errs := make([]error, n)

	jobs := make(chan chunkJob, n)
	for i, chunk := range chunks {
		jobs <- chunkJob{idx: i, chunk: chunk}
	}
	close(jobs)

	var wg sync.WaitGroup
	workers := min(e.parallel, n)
	for range workers {
		wg.Go(func() {
			e.synthesizeChunkWorker(ctx, jobs, wavData, errs, n)
		})
	}
	wg.Wait()

	return collectChunkResults(wavData, errs, n)
}

// synthesizeChunkWorker is the worker goroutine for parallel chunk synthesis.
// It reads jobs from the channel, synthesizes each chunk, and stores the
// result or error in the provided slices.
func (e *SileroEngine) synthesizeChunkWorker(
	ctx context.Context,
	jobs <-chan chunkJob,
	wavData [][]byte,
	errs []error,
	n int,
) {
	for job := range jobs {
		if ctx.Err() != nil {
			errs[job.idx] = ctx.Err()
			return
		}
		slog.Default().DebugContext(ctx, "tts.silero: synthesizing chunk",
			"chunk", job.idx+1, "of", n, "len", len(job.chunk))
		wav, err := e.synthesizeOne(ctx, job.chunk)
		if err != nil {
			errs[job.idx] = fmt.Errorf("tts.silero: chunk %d/%d: %w", job.idx+1, n, err)
			return
		}
		wavData[job.idx] = wav
	}
}

// collectChunkResults checks for errors and missing data in chunk order,
// returning the first error found or the complete wavData slice.
func collectChunkResults(wavData [][]byte, errs []error, n int) ([][]byte, error) {
	for i, err := range errs {
		if err != nil {
			return nil, err
		}
		if wavData[i] == nil {
			return nil, fmt.Errorf("tts.silero: chunk %d/%d: no data", i+1, n)
		}
	}
	return wavData, nil
}

// synthesizeOne sends a single SSML chunk to the server and returns the WAV
// bytes.
func (e *SileroEngine) synthesizeOne(ctx context.Context, text string) ([]byte, error) {
	sampleRate := e.cfg.SampleRate
	if sampleRate == 0 {
		sampleRate = 48000
	}

	body := sileroRequestBody{
		Text:       text,
		Voice:      e.cfg.Voice,
		SSML:       true,
		SampleRate: sampleRate,
		Speed:      e.cfg.Speed,
		Pitch:      e.cfg.Pitch,
	}

	bodyJSON, err := json.Marshal(body)
	if err != nil {
		return nil, fmt.Errorf("marshal request: %w", err)
	}

	url := e.serverURL + "/api/tts"
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, url, bytes.NewReader(bodyJSON))
	if err != nil {
		return nil, fmt.Errorf("create request: %w", err)
	}
	req.Header.Set("Content-Type", "application/json")

	resp, err := e.client.Do(req)
	if err != nil {
		return nil, fmt.Errorf("request failed: %w", err)
	}
	defer func() { _ = resp.Body.Close() }()

	if resp.StatusCode != http.StatusOK {
		respBody, _ := io.ReadAll(resp.Body)
		return nil, fmt.Errorf("server returned %d: %s", resp.StatusCode, string(respBody))
	}

	wav, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response: %w", err)
	}

	return wav, nil
}

// splitSSML splits SSML text into chunks of at most maxLen characters. It
// splits on sentence boundaries (</s> tags). Each chunk is wrapped in
// <speak>...</speak>. If a single sentence exceeds maxLen, it is split on
// word boundaries as a fallback.
//
// The input is expected to be <speak>...</speak> with <p> and <s> tags.
// The output chunks are <speak><s>...</s><s>...</s></speak> (paragraph
// structure is flattened — pauses are preserved by sentence breaks).
func splitSSML(ssml string) []string {
	// Extract all <s>...</s> sentence blocks.
	sentences := extractSentences(ssml)
	if len(sentences) == 0 {
		// No sentence tags found — fall back to splitting the raw text.
		return splitRaw(ssml, maxChunkLen)
	}

	var chunks []string
	var current []string
	currentLen := len("<speak></speak>") // overhead of wrapper tags

	for _, s := range sentences {
		sLen := len(s)
		// If a single sentence exceeds maxChunkLen, split it on word boundaries.
		if sLen > maxChunkLen-len("<speak></speak>") {
			if len(current) > 0 {
				chunks = append(chunks, wrapChunk(current))
				current = nil
				currentLen = len("<speak></speak>")
			}
			for _, piece := range splitSentenceOnWords(s, maxChunkLen-len("<speak></speak>")) {
				chunks = append(chunks, "<speak>"+piece+"</speak>")
			}
			continue
		}

		if currentLen+sLen > maxChunkLen && len(current) > 0 {
			chunks = append(chunks, wrapChunk(current))
			current = nil
			currentLen = len("<speak></speak>")
		}
		current = append(current, s)
		currentLen += sLen
	}

	if len(current) > 0 {
		chunks = append(chunks, wrapChunk(current))
	}

	return chunks
}

// extractSentences pulls all <s>...</s> blocks from SSML text. Returns the
// full tags (e.g., "<s>Sentence.</s>").
func extractSentences(ssml string) []string {
	var sentences []string
	idx := 0
	for {
		start := strings.Index(ssml[idx:], "<s>")
		if start < 0 {
			// Try <s ...> with attributes.
			start = strings.Index(ssml[idx:], "<s ")
			if start < 0 {
				break
			}
		}
		start += idx
		end := strings.Index(ssml[start:], "</s>")
		if end < 0 {
			break
		}
		end += start + len("</s>")
		sentences = append(sentences, ssml[start:end])
		idx = end
	}
	return sentences
}

// wrapChunk wraps sentence blocks in a <speak> root tag.
func wrapChunk(sentences []string) string {
	return "<speak>" + strings.Join(sentences, "") + "</speak>"
}

// splitSentenceOnWords splits a single <s>...</s> block on word boundaries
// when the sentence itself exceeds maxLen. Returns pieces that are each
// wrapped in <s>...</s>.
func splitSentenceOnWords(sentence string, maxLen int) []string {
	// Strip the <s> and </s> tags.
	inner := strings.TrimSpace(strings.TrimPrefix(strings.TrimSuffix(sentence, "</s>"), "<s>"))
	inner = strings.TrimPrefix(inner, "<s>") // handle <s> without attributes

	words := strings.Fields(inner)
	var pieces []string
	var current []string
	currentLen := len("<s></s>")

	for _, w := range words {
		wLen := len(w) + 1 // +1 for space
		if currentLen+wLen > maxLen && len(current) > 0 {
			pieces = append(pieces, "<s>"+strings.Join(current, " ")+"</s>")
			current = nil
			currentLen = len("<s></s>")
		}
		current = append(current, w)
		currentLen += wLen
	}
	if len(current) > 0 {
		pieces = append(pieces, "<s>"+strings.Join(current, " ")+"</s>")
	}
	return pieces
}

// splitRaw is a fallback when no <s> tags are found. It splits on sentence
// punctuation (.!?) and wraps each chunk in <speak>.
func splitRaw(text string, maxLen int) []string {
	if len(text) <= maxLen {
		return []string{text}
	}
	// Split on sentence-ending punctuation.
	var sentences []string
	start := 0
	for i := range len(text) {
		if text[i] == '.' || text[i] == '!' || text[i] == '?' {
			sentences = append(sentences, text[start:i+1])
			start = i + 1
		}
	}
	if start < len(text) {
		sentences = append(sentences, text[start:])
	}

	var chunks []string
	var current strings.Builder
	for _, s := range sentences {
		if current.Len()+len(s) > maxLen && current.Len() > 0 {
			chunks = append(chunks, current.String())
			current.Reset()
		}
		current.WriteString(s)
	}
	if current.Len() > 0 {
		chunks = append(chunks, current.String())
	}
	return chunks
}

// concatWAVs concatenates multiple WAV files into one by extracting the PCM
// data from each and writing a new WAV with the combined data. All input
// WAVs must have the same format (sample rate, channels, bits per sample).
func concatWAVs(wavs [][]byte) ([]byte, error) {
	if len(wavs) == 0 {
		return nil, fmt.Errorf("no WAV data to concatenate")
	}
	if len(wavs) == 1 {
		return wavs[0], nil
	}

	// Parse the first WAV's header to get format info.
	header, dataOffset, err := parseWAVHeader(wavs[0])
	if err != nil {
		return nil, fmt.Errorf("parse first WAV: %w", err)
	}

	// Extract PCM data from all WAVs.
	var allData []byte
	var data []byte
	for i, wav := range wavs {
		if data, err = extractWAVData(wav, dataOffset); err != nil {
			return nil, fmt.Errorf("extract data from WAV %d: %w", i+1, err)
		}
		allData = append(allData, data...)
	}

	// Build the output WAV: original header with updated sizes.
	totalLen := len(header) + len(allData)
	if totalLen > math.MaxUint32 {
		return nil, fmt.Errorf("concatenated WAV too large: %d bytes", totalLen)
	}
	if len(allData) > math.MaxUint32 {
		return nil, fmt.Errorf("WAV data too large: %d bytes", len(allData))
	}
	totalDataLen := uint32(len(allData)) //nolint:gosec // bounds-checked above
	out := make([]byte, 0, totalLen)
	out = append(out, header...)

	// Fix RIFF chunk size (file size - 8).
	binary.LittleEndian.PutUint32(out[4:8], uint32(totalLen)-chunkHeaderSize)
	// Fix data chunk size.
	dataChunkIdx := bytes.Index(out, []byte("data"))
	if dataChunkIdx >= 0 {
		binary.LittleEndian.PutUint32(out[dataChunkIdx+4:dataChunkIdx+8], totalDataLen)
	}

	out = append(out, allData...)
	return out, nil
}

// parseWAVHeader returns the header bytes (up to and including the "data"
// chunk header) and the offset where PCM data starts.
func parseWAVHeader(wav []byte) ([]byte, int, error) {
	if len(wav) < minWAVHeaderSize {
		return nil, 0, fmt.Errorf("WAV too short: %d bytes", len(wav))
	}
	if string(wav[0:4]) != wavRIFF {
		return nil, 0, fmt.Errorf("not a WAV: missing RIFF header")
	}
	if string(wav[8:12]) != wavWAVE {
		return nil, 0, fmt.Errorf("not a WAV: missing WAVE")
	}

	var dataOffset int

	// Find the "data" chunk by scanning chunks.
	offset := 12
	for offset+chunkHeaderSize <= len(wav) {
		chunkID := string(wav[offset : offset+4])
		chunkSize := binary.LittleEndian.Uint32(wav[offset+4 : offset+chunkHeaderSize])
		if chunkSize > math.MaxInt32 {
			return nil, 0, fmt.Errorf("WAV chunk size too large: %d", chunkSize)
		}
		chunkSizeInt := int(chunkSize)
		if chunkID == "data" {
			dataOffset = offset + chunkHeaderSize
			return wav[:dataOffset], dataOffset, nil
		}
		// Chunks are word-aligned (padded to even size).
		nextOffset := offset + chunkHeaderSize + chunkSizeInt
		if chunkSize%2 != 0 {
			nextOffset++
		}
		offset = nextOffset
	}

	return nil, 0, fmt.Errorf("data chunk not found in WAV")
}

// extractWAVData returns the PCM data from a WAV file, starting at the given
// data offset (from the first WAV's header). Falls back to parsing if the
// offset doesn't match.
func extractWAVData(wav []byte, expectedOffset int) ([]byte, error) {
	// Try the expected offset first (fast path — all WAVs have same header).
	if expectedOffset < len(wav) && string(wav[expectedOffset-4:expectedOffset]) == "data" {
		dataSize := binary.LittleEndian.Uint32(wav[expectedOffset-8 : expectedOffset-4])
		if dataSize > math.MaxInt32 {
			return nil, fmt.Errorf("WAV data chunk size too large: %d", dataSize)
		}
		end := min(expectedOffset+int(dataSize), len(wav))
		return wav[expectedOffset:end], nil
	}

	// Fallback: parse the header to find the data chunk.
	_, dataOffset, err := parseWAVHeader(wav)
	if err != nil {
		return nil, err
	}
	dataSize := binary.LittleEndian.Uint32(wav[dataOffset-4 : dataOffset])
	if dataSize > math.MaxInt32 {
		return nil, fmt.Errorf("WAV data chunk size too large: %d", dataSize)
	}
	end := dataOffset + int(dataSize)
	if end > len(wav) {
		return nil, fmt.Errorf("WAV data chunk truncated: declared %d bytes, have %d", dataSize, len(wav)-dataOffset)
	}
	return wav[dataOffset:end], nil
}

// CheckHealth pings the server's /health endpoint. Returns nil if the server
// is reachable and responsive.
func (e *SileroEngine) CheckHealth(ctx context.Context) error {
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, e.serverURL+"/health", nil)
	if err != nil {
		return fmt.Errorf("tts.silero: create health request: %w", err)
	}
	resp, err := e.client.Do(req)
	if err != nil {
		return fmt.Errorf("tts.silero: health check failed: %w", err)
	}
	defer func() { _ = resp.Body.Close() }()
	if resp.StatusCode != http.StatusOK {
		return fmt.Errorf("tts.silero: health check returned %d", resp.StatusCode)
	}
	return nil
}
