package tts

import (
	"bytes"
	"context"
	"encoding/binary"
	"encoding/json"
	"fmt"
	"io"
	"log/slog"
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"time"
)

// maxChunkLen is the maximum SSML text length sent to Silero in a single
// request. Silero warns at 1000 symbols and fails at longer text, so we
// stay well below that with 900.
const maxChunkLen = 900

// SileroEngine is an Engine that synthesizes speech via a remote Silero TTS
// server (biblio-tts-server-silero). It sends SSML text to the server's
// POST /api/tts endpoint and writes the returned WAV audio to the output path.
//
// The engine receives SSML text (with stress marks and <speak>/<p>/<s> tags)
// generated by the `bookai ssml` command. Silero natively supports stress
// marks (+ before the stressed vowel) and SSML tags for pause/prosody control.
//
// Long chapters are automatically split into chunks under maxChunkLen
// characters (split on sentence boundaries), synthesized separately, and the
// resulting WAV PCM data is concatenated into a single output file.
type SileroEngine struct {
	cfg       EngineConfig
	client    *http.Client
	serverURL string
	parallel  int
}

// NewSileroEngine constructs a SileroEngine from the given config. The
// ServerURL and Voice fields are required. The engine uses a 10-minute timeout
// to accommodate long chapter synthesis on first model load.
func NewSileroEngine(cfg EngineConfig) (Engine, error) {
	if cfg.ServerURL == "" {
		return nil, fmt.Errorf("tts.silero: server_url is required")
	}
	if cfg.Voice == "" {
		return nil, fmt.Errorf("tts.silero: voice is required (e.g. \"silero:v5_5_ru#xenia\")")
	}
	serverURL := strings.TrimRight(cfg.ServerURL, "/")
	parallel := cfg.Parallel
	if parallel < 1 {
		parallel = 1
	}
	return &SileroEngine{
		cfg:       cfg,
		serverURL: serverURL,
		parallel:  parallel,
		client: &http.Client{
			Timeout: 10 * time.Minute,
		},
	}, nil
}

// Name returns "silero-http".
func (e *SileroEngine) Name() string { return "silero-http" }

// sileroRequestBody is the JSON body sent to the POST /api/tts endpoint.
type sileroRequestBody struct {
	Text       string  `json:"text"`
	Voice      string  `json:"voice"`
	SSML       bool    `json:"ssml"`
	SampleRate int     `json:"sample_rate"`
	Speed      float64 `json:"speed"`
	Pitch      float64 `json:"pitch"`
}

// Synthesize sends SSML text to the Silero TTS server and writes the returned
// WAV audio to outPath. The text is expected to be SSML (with <speak> root
// tag and stress marks) generated by the `bookai ssml` command.
//
// If the text exceeds maxChunkLen characters, it is split on sentence
// boundaries (<s>...</s> tags), each chunk is synthesized separately, and the
// WAV PCM data is concatenated into a single output file.
func (e *SileroEngine) Synthesize(ctx context.Context, text string, outPath string) error {
	if text == "" {
		return fmt.Errorf("tts.silero: no text to synthesize")
	}

	chunks := splitSSML(text, maxChunkLen)
	slog.Info("tts.silero: synthesizing",
		"total_len", len(text), "chunks", len(chunks), "max_chunk_len", maxChunkLen,
		"parallel", e.parallel)

	wavData, err := e.synthesizeChunks(ctx, chunks)
	if err != nil {
		return err
	}

	if err := os.MkdirAll(filepath.Dir(outPath), 0o755); err != nil {
		return fmt.Errorf("tts.silero: create output dir: %w", err)
	}

	combined, err := concatWAVs(wavData)
	if err != nil {
		return fmt.Errorf("tts.silero: concat WAVs: %w", err)
	}

	if err := os.WriteFile(outPath, combined, 0o644); err != nil {
		return fmt.Errorf("tts.silero: write output: %w", err)
	}

	slog.Debug("tts.silero: synthesis complete", "output", outPath, "bytes", len(combined))
	return nil
}

// synthesizeChunks sends chunk requests to the server, optionally in parallel.
// Results are collected in chunk order (the order they appear in the input
// slice) so the concatenated audio preserves sentence order.
func (e *SileroEngine) synthesizeChunks(ctx context.Context, chunks []string) ([][]byte, error) {
	n := len(chunks)
	if n == 0 {
		return nil, nil
	}

	// Sequential path (default) — simple and predictable.
	if e.parallel <= 1 {
		wavData := make([][]byte, n)
		for i, chunk := range chunks {
			if ctx.Err() != nil {
				return nil, ctx.Err()
			}
			slog.Debug("tts.silero: synthesizing chunk",
				"chunk", i+1, "of", n, "len", len(chunk))
			wav, err := e.synthesizeOne(ctx, chunk)
			if err != nil {
				return nil, fmt.Errorf("tts.silero: chunk %d/%d: %w", i+1, n, err)
			}
			wavData[i] = wav
		}
		return wavData, nil
	}

	// Parallel path — send up to e.parallel chunk requests concurrently.
	wavData := make([][]byte, n)
	errs := make([]error, n)

	type chunkJob struct {
		idx   int
		chunk string
	}

	jobs := make(chan chunkJob, n)
	for i, chunk := range chunks {
		jobs <- chunkJob{idx: i, chunk: chunk}
	}
	close(jobs)

	var wg sync.WaitGroup
	workers := e.parallel
	if workers > n {
		workers = n
	}
	for w := 0; w < workers; w++ {
		wg.Add(1)
		go func() {
			defer wg.Done()
			for job := range jobs {
				if ctx.Err() != nil {
					errs[job.idx] = ctx.Err()
					return
				}
				slog.Debug("tts.silero: synthesizing chunk",
					"chunk", job.idx+1, "of", n, "len", len(job.chunk))
				wav, err := e.synthesizeOne(ctx, job.chunk)
				if err != nil {
					errs[job.idx] = fmt.Errorf("tts.silero: chunk %d/%d: %w", job.idx+1, n, err)
					return
				}
				wavData[job.idx] = wav
			}
		}()
	}
	wg.Wait()

	// Check for errors — return the first one in chunk order.
	for i, err := range errs {
		if err != nil {
			return nil, err
		}
		if wavData[i] == nil {
			return nil, fmt.Errorf("tts.silero: chunk %d/%d: no data", i+1, n)
		}
	}

	return wavData, nil
}

// synthesizeOne sends a single SSML chunk to the server and returns the WAV
// bytes.
func (e *SileroEngine) synthesizeOne(ctx context.Context, text string) ([]byte, error) {
	sampleRate := e.cfg.SampleRate
	if sampleRate == 0 {
		sampleRate = 48000
	}

	body := sileroRequestBody{
		Text:       text,
		Voice:      e.cfg.Voice,
		SSML:       true,
		SampleRate: sampleRate,
		Speed:      e.cfg.Speed,
		Pitch:      e.cfg.Pitch,
	}

	bodyJSON, err := json.Marshal(body)
	if err != nil {
		return nil, fmt.Errorf("marshal request: %w", err)
	}

	url := e.serverURL + "/api/tts"
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, url, bytes.NewReader(bodyJSON))
	if err != nil {
		return nil, fmt.Errorf("create request: %w", err)
	}
	req.Header.Set("Content-Type", "application/json")

	resp, err := e.client.Do(req)
	if err != nil {
		return nil, fmt.Errorf("request failed: %w", err)
	}
	defer func() { _ = resp.Body.Close() }()

	if resp.StatusCode != http.StatusOK {
		respBody, _ := io.ReadAll(resp.Body)
		return nil, fmt.Errorf("server returned %d: %s", resp.StatusCode, string(respBody))
	}

	wav, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response: %w", err)
	}

	return wav, nil
}

// splitSSML splits SSML text into chunks of at most maxLen characters. It
// splits on sentence boundaries (</s> tags). Each chunk is wrapped in
// <speak>...</speak>. If a single sentence exceeds maxLen, it is split on
// word boundaries as a fallback.
//
// The input is expected to be <speak>...</speak> with <p> and <s> tags.
// The output chunks are <speak><s>...</s><s>...</s></speak> (paragraph
// structure is flattened — pauses are preserved by sentence breaks).
func splitSSML(ssml string, maxLen int) []string {
	// Extract all <s>...</s> sentence blocks.
	sentences := extractSentences(ssml)
	if len(sentences) == 0 {
		// No sentence tags found — fall back to splitting the raw text.
		return splitRaw(ssml, maxLen)
	}

	var chunks []string
	var current []string
	currentLen := len("<speak></speak>") // overhead of wrapper tags

	for _, s := range sentences {
		sLen := len(s)
		// If a single sentence exceeds maxLen, split it on word boundaries.
		if sLen > maxLen-len("<speak></speak>") {
			if len(current) > 0 {
				chunks = append(chunks, wrapChunk(current))
				current = nil
				currentLen = len("<speak></speak>")
			}
			for _, piece := range splitSentenceOnWords(s, maxLen-len("<speak></speak>")) {
				chunks = append(chunks, "<speak>"+piece+"</speak>")
			}
			continue
		}

		if currentLen+sLen > maxLen && len(current) > 0 {
			chunks = append(chunks, wrapChunk(current))
			current = nil
			currentLen = len("<speak></speak>")
		}
		current = append(current, s)
		currentLen += sLen
	}

	if len(current) > 0 {
		chunks = append(chunks, wrapChunk(current))
	}

	return chunks
}

// extractSentences pulls all <s>...</s> blocks from SSML text. Returns the
// full tags (e.g., "<s>Sentence.</s>").
func extractSentences(ssml string) []string {
	var sentences []string
	idx := 0
	for {
		start := strings.Index(ssml[idx:], "<s>")
		if start < 0 {
			// Try <s ...> with attributes.
			start = strings.Index(ssml[idx:], "<s ")
			if start < 0 {
				break
			}
		}
		start += idx
		end := strings.Index(ssml[start:], "</s>")
		if end < 0 {
			break
		}
		end += start + len("</s>")
		sentences = append(sentences, ssml[start:end])
		idx = end
	}
	return sentences
}

// wrapChunk wraps sentence blocks in a <speak> root tag.
func wrapChunk(sentences []string) string {
	return "<speak>" + strings.Join(sentences, "") + "</speak>"
}

// splitSentenceOnWords splits a single <s>...</s> block on word boundaries
// when the sentence itself exceeds maxLen. Returns pieces that are each
// wrapped in <s>...</s>.
func splitSentenceOnWords(sentence string, maxLen int) []string {
	// Strip the <s> and </s> tags.
	inner := strings.TrimSpace(strings.TrimPrefix(strings.TrimSuffix(sentence, "</s>"), "<s>"))
	inner = strings.TrimPrefix(inner, "<s>") // handle <s> without attributes

	words := strings.Fields(inner)
	var pieces []string
	var current []string
	currentLen := len("<s></s>")

	for _, w := range words {
		wLen := len(w) + 1 // +1 for space
		if currentLen+wLen > maxLen && len(current) > 0 {
			pieces = append(pieces, "<s>"+strings.Join(current, " ")+"</s>")
			current = nil
			currentLen = len("<s></s>")
		}
		current = append(current, w)
		currentLen += wLen
	}
	if len(current) > 0 {
		pieces = append(pieces, "<s>"+strings.Join(current, " ")+"</s>")
	}
	return pieces
}

// splitRaw is a fallback when no <s> tags are found. It splits on sentence
// punctuation (.!?) and wraps each chunk in <speak>.
func splitRaw(text string, maxLen int) []string {
	if len(text) <= maxLen {
		return []string{text}
	}
	// Split on sentence-ending punctuation.
	var sentences []string
	start := 0
	for i := 0; i < len(text); i++ {
		if text[i] == '.' || text[i] == '!' || text[i] == '?' {
			sentences = append(sentences, text[start:i+1])
			start = i + 1
		}
	}
	if start < len(text) {
		sentences = append(sentences, text[start:])
	}

	var chunks []string
	var current strings.Builder
	for _, s := range sentences {
		if current.Len()+len(s) > maxLen && current.Len() > 0 {
			chunks = append(chunks, current.String())
			current.Reset()
		}
		current.WriteString(s)
	}
	if current.Len() > 0 {
		chunks = append(chunks, current.String())
	}
	return chunks
}

// concatWAVs concatenates multiple WAV files into one by extracting the PCM
// data from each and writing a new WAV with the combined data. All input
// WAVs must have the same format (sample rate, channels, bits per sample).
func concatWAVs(wavs [][]byte) ([]byte, error) {
	if len(wavs) == 0 {
		return nil, fmt.Errorf("no WAV data to concatenate")
	}
	if len(wavs) == 1 {
		return wavs[0], nil
	}

	// Parse the first WAV's header to get format info.
	header, dataOffset, fmtInfo, err := parseWAVHeader(wavs[0])
	if err != nil {
		return nil, fmt.Errorf("parse first WAV: %w", err)
	}

	// Extract PCM data from all WAVs.
	var allData []byte
	for i, wav := range wavs {
		data, err := extractWAVData(wav, dataOffset)
		if err != nil {
			return nil, fmt.Errorf("extract data from WAV %d: %w", i+1, err)
		}
		allData = append(allData, data...)
	}

	// Build the output WAV: original header with updated sizes.
	totalDataLen := uint32(len(allData))
	out := make([]byte, 0, len(header)+len(allData))
	out = append(out, header...)

	// Fix RIFF chunk size (file size - 8).
	binary.LittleEndian.PutUint32(out[4:8], uint32(len(header)+len(allData))-8)
	// Fix data chunk size.
	dataChunkIdx := bytes.Index(out, []byte("data"))
	if dataChunkIdx >= 0 {
		binary.LittleEndian.PutUint32(out[dataChunkIdx+4:dataChunkIdx+8], totalDataLen)
	}

	out = append(out, allData...)
	_ = fmtInfo // format info is preserved from the first WAV's header
	return out, nil
}

// parseWAVHeader returns the header bytes (up to and including the "data"
// chunk header), the offset where PCM data starts, and the format info.
func parseWAVHeader(wav []byte) (header []byte, dataOffset int, fmtInfo wavFmt, err error) {
	if len(wav) < 44 {
		return nil, 0, wavFmt{}, fmt.Errorf("WAV too short: %d bytes", len(wav))
	}
	if string(wav[0:4]) != "RIFF" {
		return nil, 0, wavFmt{}, fmt.Errorf("not a WAV: missing RIFF header")
	}
	if string(wav[8:12]) != "WAVE" {
		return nil, 0, wavFmt{}, fmt.Errorf("not a WAV: missing WAVE")
	}

	// Find the "data" chunk by scanning chunks.
	offset := 12
	for offset+8 <= len(wav) {
		chunkID := string(wav[offset : offset+4])
		chunkSize := binary.LittleEndian.Uint32(wav[offset+4 : offset+8])
		if chunkID == "data" {
			dataOffset = offset + 8
			return wav[:dataOffset], dataOffset, fmtInfo, nil
		}
		if chunkID == "fmt " {
			if offset+8+int(chunkSize) <= len(wav) {
				fmtInfo = parseFmtChunk(wav[offset+8 : offset+8+int(chunkSize)])
			}
		}
		// Chunks are word-aligned (padded to even size).
		nextOffset := offset + 8 + int(chunkSize)
		if chunkSize%2 != 0 {
			nextOffset++
		}
		offset = nextOffset
	}

	return nil, 0, wavFmt{}, fmt.Errorf("data chunk not found in WAV")
}

// wavFmt holds the audio format from the fmt chunk.
type wavFmt struct {
	AudioFormat   uint16
	NumChannels   uint16
	SampleRate    uint32
	BitsPerSample uint16
}

// parseFmtChunk extracts format info from the fmt chunk data.
func parseFmtChunk(data []byte) wavFmt {
	if len(data) < 16 {
		return wavFmt{}
	}
	return wavFmt{
		AudioFormat:   binary.LittleEndian.Uint16(data[0:2]),
		NumChannels:   binary.LittleEndian.Uint16(data[2:4]),
		SampleRate:    binary.LittleEndian.Uint32(data[4:8]),
		BitsPerSample: binary.LittleEndian.Uint16(data[14:16]),
	}
}

// extractWAVData returns the PCM data from a WAV file, starting at the given
// data offset (from the first WAV's header). Falls back to parsing if the
// offset doesn't match.
func extractWAVData(wav []byte, expectedOffset int) ([]byte, error) {
	// Try the expected offset first (fast path — all WAVs have same header).
	if expectedOffset < len(wav) && string(wav[expectedOffset-4:expectedOffset]) == "data" {
		dataSize := binary.LittleEndian.Uint32(wav[expectedOffset-8 : expectedOffset-4])
		end := expectedOffset + int(dataSize)
		if end > len(wav) {
			end = len(wav)
		}
		return wav[expectedOffset:end], nil
	}

	// Fallback: parse the header to find the data chunk.
	_, dataOffset, _, err := parseWAVHeader(wav)
	if err != nil {
		return nil, err
	}
	dataSize := binary.LittleEndian.Uint32(wav[dataOffset-4 : dataOffset])
	end := dataOffset + int(dataSize)
	if end > len(wav) {
		end = len(wav)
	}
	return wav[dataOffset:end], nil
}

// CheckHealth pings the server's /health endpoint. Returns nil if the server
// is reachable and responsive.
func (e *SileroEngine) CheckHealth(ctx context.Context) error {
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, e.serverURL+"/health", nil)
	if err != nil {
		return fmt.Errorf("tts.silero: create health request: %w", err)
	}
	resp, err := e.client.Do(req)
	if err != nil {
		return fmt.Errorf("tts.silero: health check failed: %w", err)
	}
	defer func() { _ = resp.Body.Close() }()
	if resp.StatusCode != http.StatusOK {
		return fmt.Errorf("tts.silero: health check returned %d", resp.StatusCode)
	}
	return nil
}

func init() {
	Register("silero-http", NewSileroEngine)
}
